
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: heroku_kadai_development

test:
  <<: *default
  database: heroku_kadai_test

production:
  <<: *default
  database: heroku_kadai_production
  username: heroku_kadai
  password: <%= ENV['HEROKU_KADAI_DATABASE_PASSWORD'] %>
